sudo: required
dist: trusty
cache: bundler
language: ruby
rvm:
  - 2.3.0
env:
  - DOCKER_VERSION=1.10.0
before_install: ./script/install_dependencies.sh
before_script:
 - export PATH=/opt/docker:$PATH
 - docker version
